[profile.default]
cache_path = "forge-cache"
evm_version = "cancun"
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
out = "forge-out"
script = "scripts"
solc_version = "0.8.30"
src = "contracts"
test = "test"

[rpc_endpoints]
l1 = "http://127.0.0.1:9545"
l2 = "http://127.0.0.1:9546"
